# Debizium SQL Server Source Connector (CDC)

connectors:
    - name: "debezium_src_cdc_0"
      config:
        connector.class: "dddd"

    - name: "debezium_src_cdc_1"
      config:
        connector.class: "dddd"

common:
  config: {
      "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector",
      "tasks.max": "1",  # default  # 디비지움은 1개만 가능?

      "database.hostname": "{db_ip}",
      "database.port": "{db_port}",
      "database.user": "{db_user}",
      "database.password": "{db_pass}",
      "database.dbname": "{db_name}",

      "topic.prefix": "fullfillment",
      "table.include.list": "dbo.customers",
      "schema.history.internal.kafka.bootstrap.servers": "kafka:9092",
      "schema.history.internal.kafka.topic": "schemahistory.fullfillment",
      "database.ssl.truststore": "path/to/trust-store",
      "database.ssl.truststore.password": "password-for-trust-store",
  }


