

connectors:
    - name: "test_get_transaction_isolation"
      config:
        query:
          "SELECT CASE transaction_isolation_level
              WHEN 0 THEN 'Unspecified'
              WHEN 1 THEN 'ReadUncommitted'
              WHEN 2 THEN 'ReadCommitted'
              WHEN 3 THEN 'Repeatable'
              WHEN 4 THEN 'Serializable'
              WHEN 5 THEN 'Snapshot' END AS TRANSACTION_ISOLATION_LEVEL
          FROM sys.dm_exec_sessions
          where session_id = @@SPID"
    - name: "test_binary_checksum"
      config:
        query: |
          SELECT (BINARY_CHECKSUM(*)) FROM TutorialDB.dbo.Customers
    - name: "test_openrowset_bulk"
      config:
        query: |
          SELECT * FROM OPENROWSET(BULK '/home/ubuntu/temp.txt', SINGLE_CLOB)
          AS Contents
    #- name: "test_query"
    #  config:
    #    query: ""
